on:
  push:
    branches: [ 'main' ]

jobs:
  core:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: gradle jar --refresh-dependencies
      - name: Deploy project to artifactory
        run: gradle publish
      - name: Deploy to remote servers
        run: |
          sh /home/cloud/scripts/services/github/actions/deploy.sh core-spigot/build/libs/core-spigot.jar
          sh /home/cloud/scripts/services/github/actions/deploy.sh core-bungee/build/libs/core-bungee.jar