on:
  push:
    branches: [ 'main' ]

jobs:
  core:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew shadowJar
      - name: Deploy project to artifactory
        run: ./gradlew publish
      - name: Deploy to remote servers
        run: |
          sh /home/cloud/scripts/github/deploy.sh core-spigot/build/libs/core-spigot.jar
          sh /home/cloud/scripts/github/deploy.sh core-bungee/build/libs/core-bungee.jar