on: [ 'push' ]

jobs:
  core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Shadow archive
      run: ./gradlew shadowJar
    - name: Publish to maven local
      run: ./gradlew publishToMavenLocal
    - name: Deploy to all servers
      uses: hyrendev/scp-action@main
      with:
        key: ${{ secrets.DEDICATED_SSH_KEY }}
        host: ${{ secrets.DEDICATED_1_HOST_ADDRESS }}
        scp: |
            /home/cloud/output/core-spigot.jar:~/root/core-spigot.jar
