on:
  push:
    branches: [ 'main' ]

jobs:
  core:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew shadowJar
      - name: Deploy project
        run: ./gradlew publish
      - name: Deploy to remote servers
        uses: HyrenDev/scp-action@main
        with:
          files: |
            core-spigot/build/libs/core-spigot.jar
            core-bungee/build/libs/core-bungee.jar
