on: [ 'push' ]

jobs:
  core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build project
      run: ./gradlew shadowJar
    - name: Deploy project
      run: ./gradlew publish
    - name: Deploy to all servers
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ${{ github.workspace }}/bootstrap/target/Waterfall.jar
        remote: ${{ secrets.CLOUD_OUTPUT_REPOSITORY }}/waterfall.jar
        host: ${{ secrets.DEDICATED_1_HOST_ADDRESS }}
        username: ${{ secrets.DEDICATED_USER }}
        privateKey: ${{ secrets.DEDICATED_SSH_KEY }}
