on: [ 'push' ]

jobs:
  core:
    runs-on: ubuntu-latest

    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean project
      run: ./gradlew clean
    - name: Delete old versions of this package
      uses: actions/delete-package-versions@v1
      with:
        owner: hyrendev
        repo: nexus
        package-name: |
          com.redefantasy.core-bungee
          com.redefantasy.core-shared
          com.redefantasy.core-spigot
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Deploy project
      run: ./gradlew publish