on: [ 'push' ]

jobs:
  core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - uses: s4u/maven-settings-action@v2.4.0
      with:
        servers: |
          [{
            "id": ${{ secrets.MAVEN_ID }},
            "username": ${{ secrets.MAVEN_USERNAME }},
            "password": ${{ secrets.MAVEN_PASSWORD }}
          }]
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean project
      run: ./gradlew clean
    - name: Build project
      run: ./gradlew shadowJar -Pmaven-username=Gutyerrez -Pmaven-password=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
    - name: Deploy project
      run: ./gradlew publish -Pmaven-username=Gutyerrez -Pmaven-password=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
    - name: Deploy to all servers
      uses: garygrossgarten/github-action-scp@release
      with:
        local: |
          ${{ github.workspace }}/core-bungee/build/libs/core-bungee.jar
          ${{ github.workspace }}/core-shared/build/libs/core-shared.jar
          ${{ github.workspace }}/core-spigot/build/libs/core-spigot.jar
        remote: ${{ secrets.CLOUD_OUTPUT_REPOSITORY }}/core-bungee.jar
        host: ${{ secrets.DEDICATED_1_HOST_ADDRESS }}
        username: ${{ secrets.DEDICATED_USER }}
        privateKey: ${{ secrets.DEDICATED_SSH_KEY }}
