on: [ 'push' ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean project
        run: ./gradlew clean
      - name: Build project
        run: ./gradlew shadowJar
      - name: Delete old versions of this packages
        uses: hyrendev/delete-packages-version-action@0.1-ALPHA
        with:
          owner: ${{ secrets.OWNER }}
          repository: ${{ secrets.NEXUS }}
          token: ${{ secrets.ACCESS_TOKEN }}
          packages: |
            [
              "com.redefantasy.core-bungee",
              "com.redefantasy.core-shared",
              "com.redefantasy.core-spigot"
            ]
      - name: Await all deleted packages propagation
        uses: jakejarvis/wait-action@master
        with:
          time: 15s
      - name: Deploy project
        run: ./gradlew publish
      - name: List folders
        run: |
          ls -ln && cd core-bungee/ && ls -ln && cd build && ls -ln
          cd ${{ github.workspace }}
          ls -ln && cd core-spigot/ && ls -ln && cd build && ls -ln
      - name: Deploy project to remote servers
        uses: hyrendev/scp-action@0.1-ALPHA
        with:
          files: |
            [
              "core-bungee/build/libs/core-bungee.jar",
              "core-spigot/build/libs/core-spigot.jar"
            ]
          remote: /home/cloud/output/
          servers: |
            [
              {
                "host": "${{ secrets.DEDICATED_1_HOST_ADDRESS }}",
                "port": "${{ secrets.DEDICATED_PORT }}",
                "user": "${{ secrets.DEDICATED_USER }}",
                "private_key": "${{ secrets.DEDICATED_SSH_KEY }}"
              }
            ]
