on:
  push:
    branches: [ 'main' ]

jobs:
  core:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew shadowJar
      - name: Deploy project
        run: ./gradlew publish