on: [ 'push' ]

jobs:
  update-project-to-latest-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
  clean:
    runs-on: ubuntu-latest

    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean project
        run: ./gradlew clean
      - name: List folders
        run: ls -ln
  delete-old-versions-of-this-package:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old versions of this packages
        uses: hyrendev/delete-packages-version-action@0.1-ALPHA
        with:
          owner: ${{ secrets.OWNER }}
          repository: ${{ secrets.NEXUS }}
          token: ${{ secrets.ACCESS_TOKEN }}
          packages: |
            [
              "com.redefantasy.core-bungee",
              "com.redefantasy.core-shared",
              "com.redefantasy.core-spigot"
            ]
  deploy-to-github-packages:
    runs-on: ubuntu-latest

    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
      - name: Deploy project
        run: ./gradlew publish
  deploy-to-remote-servers:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy project to remote servers
        uses: hyrendev/scp-action@0.1-ALPHA
        with:
          files: |
            [
              "${{ github.workspace }}/core-bungee/builds/libs/core-bungee.jar",
              "${{ github.workspace }}/core-spigot/builds/libs/core-spigot.jar"
            ]
          remote: /home/cloud/output/
          servers: |
            [
              {
                "host": "${{ secrets.DEDICATED_1_HOST_ADDRESS }}",
                "port": "${{ secrets.DEDICATED_PORT }}",
                "user": "${{ secrets.DEDICATED_USER }}",
                "private_key": "${{ secrets.DEDICATED_SSH_KEY }}"
              }
            ]
